export const ACTION_TYPE = {
	INIT_VIDEOS: "INIT_VIDEOS",
	SORT_BY: "SORT_BY",
	SORTBY_DATE: "SORTBY_DATE",
	ADD_COMMENT: "ADD_COMMENT",
	WATCH_LATER: "WATCH_LATER",
	LIKE_VIDEO: "LIKE_VIDEO",
	HISTORY_VIDEO: "HISTORY_VIDEO",
	SEARCH: "SEARCH",
};
